version: '3'
services:

  yesido:
    image: php:7.4-fpm
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www

  composer:
    image: composer:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
