version: '3'
services:

  webservice:
    build:
        context: ./docker
        dockerfile: Dockerfile
    ports:
      - 80:80
    working_dir: /var/www
    tty: true
    volumes:
      - ./web:/var/www/html

  composer:
    image: composer:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
