version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www

  composer:
    image: composer:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
